package com.minjeok4go.petplace.common.constant;

import lombok.Getter;

@Getter
public enum Breed {
    // DOG
    AFFENPINSCHER("아펜핀셔"),
    AFGHAN_HOUND("아프간 하운드"),
    AIREDALE("에어데일 테리어"),
    AKITA("아키타"),
    APPENZELLER("아펜젤러"),
    AUSTRALIAN_TERRIER("오스트레일리언 테리어"),
    BASENJI("바센지"),
    BASSET("바셋 하운드"),
    BEAGLE("비글"),
    BEDLINGTON_TERRIER("베들링턴 테리어"),
    BERNESE_MOUNTAIN_DOG("버니즈 마운틴 독"),
    BLACK_AND_TAN_COONHOUND("블랙 앤 탄 쿤하운드"),
    BLENHEIM_SPANIEL("블레넘 스패니얼"),
    BLOODHOUND("블러드하운드"),
    BORDER_COLLIE("보더 콜리"),
    BORDER_TERRIER("보더 테리어"),
    BORZOI("보르조이"),
    BOSTON_BULL("보스턴 테리어"),
    BOUVIER_DES_FLANDRES("부비에 데 플랑드르"),
    BOXER("복서"),
    BRABANCON_GRIFFON("브라반손 그리폰"),
    BRIARD("브리아드"),
    BRITTANY_SPANIEL("브리타니 스패니얼"),
    BULL_MASTIFF("불마스티프"),
    CAIRN("케언 테리어"),
    CARDIGAN("카디건 웰시 코기"),
    CHESAPEAKE_BAY_RETRIEVER("체서피크 베이 리트리버"),
    CHIHUAHUA("치와와"),
    CHOW("차우차우"),
    CLUMBER("클럼버 스패니얼"),
    COCKER_SPANIEL("코커 스패니얼"),
    COLLIE("콜리"),
    CURLY_COATED_RETRIEVER("컬리 코티드 리트리버"),
    DANDIE_DINMONT("댄디 딘몬트 테리어"),
    DHOLE("도레(아시아 야생개)"),
    DINGO("딩고"),
    DOBERMAN("도베르만"),
    ENGLISH_FOXHOUND("잉글리시 폭스하운드"),
    ENGLISH_SETTER("잉글리시 세터"),
    ENGLISH_SPRINGER("잉글리시 스프링거 스패니얼"),
    ENTLEBUCHER("엔틀부허 마운틴 독"),
    ESKIMO_DOG("에스키모 도그"),
    FLAT_COATED_RETRIEVER("플랫 코티드 리트리버"),
    FRENCH_BULLDOG("프렌치 불도그"),
    GERMAN_SHEPHERD("저먼 셰퍼드"),
    GERMAN_SHORT_HAIRED_POINTER("저먼 쇼트헤어드 포인터"),
    GIANT_SCHNAUZER("자이언트 슈나우저"),
    GOLDEN_RETRIEVER("골든 리트리버"),
    GORDON_SETTER("고든 세터"),
    GREAT_DANE("그레이트 데인"),
    GREAT_PYRENEES("그레이트 피레니즈"),
    GREATER_SWISS_MOUNTAIN_DOG("그레이터 스위스 마운틴 독"),
    GROENENDAEL("그루넨달"),
    IBIZAN_HOUND("이비자 하운드"),
    IRISH_SETTER("아이리시 세터"),
    IRISH_TERRIER("아이리시 테리어"),
    IRISH_WATER_SPANIEL("아이리시 워터 스패니얼"),
    IRISH_WOLFHOUND("아이리시 울프하운드"),
    ITALIAN_GREYHOUND("이탈리안 그레이하운드"),
    JAPANESE_SPANIEL("일본 스패니얼"),
    KEESHOND("키스혼드"),
    KELPIE("켈피"),
    KERRY_BLUE_TERRIER("케리 블루 테리어"),
    KOMONDOR("코몬도르"),
    KUVASZ("쿠바즈"),
    LABRADOR_RETRIEVER("래브라도 리트리버"),
    LAKELAND_TERRIER("레이클랜드 테리어"),
    LEONBERG("레온베르거"),
    LHASA("라사 압소"),
    MALAMUTE("알래스칸 말라뮤트"),
    MALINOIS("말리노이즈"),
    MALTESE_DOG("말티즈"),
    MEXICAN_HAIRLESS("멕시칸 헤어리스 도그"),
    MINIATURE_PINSCHER("미니어처 핀셔"),
    MINIATURE_POODLE("미니어처 푸들"),
    MINIATURE_SCHNAUZER("미니어처 슈나우저"),
    NEWFOUNDLAND("뉴펀들랜드"),
    NORFOLK_TERRIER("노퍽 테리어"),
    NORWEGIAN_ELKHOUND("노르웨이 엘크하운드"),
    NORWICH_TERRIER("노리치 테리어"),
    OLD_ENGLISH_SHEEPDOG("올드 잉글리시 쉽독"),
    OTTERHOUND("오터하운드"),
    PAPILLON("파피용"),
    PEKINESE("페키니즈"),
    PEMBROKE("펨브록 웰시 코기"),
    POMERANIAN("포메라니안"),
    PUG("퍼그"),
    REDBONE("레드본 쿤하운드"),
    RHODESIAN_RIDGEBACK("로디지안 리지백"),
    ROTTWEILER("로트와일러"),
    SAINT_BERNARD("세인트 버나드"),
    SALUKI("살루키"),
    SAMOYED("사모예드"),
    SCHIPPERKE("스키퍼키"),
    SCOTCH_TERRIER("스코티시 테리어"),
    SCOTTISH_DEERHOUND("스코티시 디어하운드"),
    SEALYHAM_TERRIER("실리햄 테리어"),
    SHETLAND_SHEEPDOG("셰틀랜드 쉽독"),
    SHIH_TZU("시추"),
    SIBERIAN_HUSKY("시베리안 허스키"),
    SILKY_TERRIER("실키 테리어"),
    SOFT_COATED_WHEATEN_TERRIER("소프트 코티드 휘튼 테리어"),
    STAFFORDSHIRE_BULLTERRIER("스태퍼드셔 불테리어"),
    STANDARD_POODLE("스탠다드 푸들"),
    STANDARD_SCHNAUZER("스탠다드 슈나우저"),
    SUSSEX_SPANIEL("서식스 스패니얼"),
    TIBETAN_MASTIFF("티베탄 마스티프"),
    TIBETAN_TERRIER("티베탄 테리어"),
    TOY_POODLE("토이 푸들"),
    TOY_TERRIER("토이 테리어"),
    VIZSLA("비즐라"),
    WALKER_HOUND("워커 하운드"),
    WEIMARANER("와이마라너"),
    WELSH_SPRINGER_SPANIEL("웰시 스프링거 스패니얼"),
    WEST_HIGHLAND_WHITE_TERRIER("웨스트 하이랜드 화이트 테리어"),
    WHIPPET("휘핏"),
    WIRE_HAIRED_FOX_TERRIER("와이어헤어드 폭스 테리어"),
    YORKSHIRE_TERRIER("요크셔 테리어"),

    // CAT
    KOREAN_SHORTHAIR("코리안 숏헤어"),
    RUSSIAN_BLUE("러시안 블루"),
    PERSIAN("페르시안"),
    SIAMESE("샴"),
    MUNCHKIN("먼치킨"),
    SCOTTISH_FOLD("스코티시 폴드"),
    RAGDOLL("랙돌"),
    KOREAN_MEDIUMHAIR("코리안 미디엄헤어"),
    AMERICAN_SHORTHAIR("아메리칸 숏헤어"),
    DOMESTIC_LONG_HAIR("코리안 롱헤어"),
    TORTOISESHELL("토터셸"),
    CALICO("칼리코"),
    TORBIE("토비"),
    DILUTE_CALICO("다일루트 칼리코"),
    TUXEDO("턱시도"),
    DILUTE_TORTOISESHELL("다일루트 토터셸"),
    TABBY("태비"),
    MAINE_COON("메인 쿤"),
    BENGAL("벵갈"),
    NORWEGIAN_FOREST("노르웨이 숲"),

    // RABBIT
    NETHERLAND_DWARF("네덜란드 드워프"),
    MINI_REX("미니 렉스"),
    LIONHEAD("라이언헤드"),

    // HAMSTER
    GOLDEN_HAMSTER("골든 햄스터"),
    TEDDY_BEAR_HAMSTER("테디베어 햄스터"),
    CAMPBELL_DWARF("캠벨 햄스터"),
    WINTER_WHITE_DWARF("윈터 화이트 햄스터"),
    PEARL_WINTER_WHITE_DWARF("펄 윈터 화이트 햄스터"),
    ROBOROVSKI_DWARF("로보로브스키 햄스터"),
    CHINESE_HAMSTER("차이니즈 햄스터"),

    // BIRD
    BUDGERIGAR("잉꼬"),
    COCKATIEL("왕관앵무"),
    LOVE_BIRD("모란앵무"),
    AFRICAN_GREY_PARROT("아프리칸 그레이 패럿"),
    MACAW("금강앵무"),
    COCKATOO("코카투"),
    CONURE("코뉴어"),
    PARROTLET("패럿렛"),
    AMAZON_PARROT("아마존앵무"),
    RINGNECK_PARAKEET("링넥 파라킷"),
    CANARY("카나리아"),
    ZEBRA_FINCH("주홍얼굴 핀치"),
    JAVA_FINCH("화이트 자바 핀치"),
    SOCIETY_FINCH("분홍얼굴 핀치"),
    GOULDIAN_FINCH("구르디안 핀치"),

    // REPTILE
    LEOPARD_GECKO("레오파드 게코"),
    CRESTED_GECKO("크레스티드 게코"),
    BEARDED_DRAGON("비어디 드래곤"),

    // 기타
    UNKNOWN("기타");

    private final String displayName;

    Breed(String displayName) { this.displayName = displayName; }
}
