package com.minjeok4go.petplace.common.constant;

public enum Breed {
    // DOG
    POMERANIAN, MALTESE, POODLE, CHIHUAHUA, BICHON_FRISE,
    SHIBA_INU, GOLDEN_RETRIEVER, LABRADOR_RETRIEVER, SIBERIAN_HUSKY,
    DACHSHUND, BULLDOG, COCKER_SPANIEL, YORKSHIRE_TERRIER,
    // CAT
    KOREAN_SHORTHAIR, RUSSIAN_BLUE, SIAMESE, PERSIAN,
    SCOTTISH_FOLD, MAINE_COON, BENGAL, NORWEGIAN_FOREST,
    // RABBIT
    NETHERLAND_DWARF, MINI_REX, LIONHEAD,
    // HAMSTER
    GOLDEN_HAMSTER, DWARF_HAMSTER, ROBOROVSKI,
    // BIRD
    LOVEBIRD, COCKATIEL, BUDGERIGAR,
    // TURTLE
    RUSSIAN_TORTOISE, RED_EARED_SLIDER,
    // REPTILE
    LEOPARD_GECKO, BEARDED_DRAGON,
    // 기타
    UNKNOWN
}
